Drop an informative error message for towncrier failures
beeware/.github pull request #63
Opened 2023-11-02 23:37 UTC by rmartin16

## Changes
- First time contributors are often left adrift by the towncrier check failure in CI...so, this adds a more informative error message to help them resolve the issue without intervention.
- Example failure: https://github.com/beeware/briefcase/actions/runs/6739392185/job/18320777204
- Example success: https://github.com/beeware/briefcase/actions/runs/6739401915/job/18320801738

## Notes
- I just choose the Toga documentation....but we can point people elsewhere. The documentation is a bit dense given we're just asking for a quick blurb....but one thing at a time I suppose.
- Open to reformatting the error message

## PR Checklist:

- [X] All new features have been tested
- [X] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

2023-11-03 01:14 UTC, freakboy3742 requested changes
This looks like it should be a good improvement. My only hesitation is the hard reference to Toga's docs - firstly because it's going to be a little weird to have references to Toga's docs in a Briefcase build; but also, as you note, the Toga docs are a little dense.

I wonder if a better approach might be a page on the BeeWare website? We already have a (woefully out of date) general contribution guide; this would be a good opportunity to have a general cleanup there, and include a single purpose "So you've got an error about TownCrier..." page.

2023-11-10 19:48 UTC, rmartin16 commented
reminder for when i get back around to this....consider a similar message for `pre-commit` failures

2024-01-29 17:31 UTC, rmartin16 commented
Once https://github.com/beeware/beeware.github.io/pull/551 is merged, this is ready to go.

2024-01-30 04:08 UTC, freakboy3742 approved these changes

2024-01-30 04:08 UTC, merged